language: objective-c

cache:
  directories:
  - downloads/

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.8.0"

# -nc means only download if it doesn't exist
# -P puts it in the cached download directory
before_install:
 - wget -nc -P "downloads/" "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "downloads/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
 - xbuild XamarinProject/XamarinProject.sln 
 - ci/nunit.sh XamarinProject/UnityTools/bin/Debug/UnityTools.dll

